import { baamText } from "./companion";
import type { WorkflowField } from "./workflows";
export const workflowLabels: Record<string, [string, string, string]> = {
  qtyDelta: ["Изменение количества (+/−)", "Quantity change (+/−)", "Сандын өзгөрүшү (+/−)"],
  targetOnHand: ["Фактический остаток", "Actual stock", "Иш жүзүндөгү калдык"],
  comment: ["Комментарий", "Comment", "Түшүндүрмө"],
  shiftId: ["Открытая смена", "Open shift", "Ачык смена"],
  name: ["Название", "Name", "Аталышы"],
  storeId: ["Магазин", "Store", "Дүкөн"],
  fromStoreId: ["Откуда", "From store", "Кайсы дүкөндөн"],
  toStoreId: ["Куда", "To store", "Кайсы дүкөнгө"],
  sourceStoreId: ["Откуда", "From store", "Кайсы дүкөндөн"],
  destinationStoreId: ["Куда", "To store", "Кайсы дүкөнгө"],
  baseUnitId: ["Единица измерения", "Unit", "Өлчөө бирдиги"],
  basePriceKgs: ["Цена продажи, KGS", "Selling price, KGS", "Сатуу баасы, KGS"],
  purchasePriceKgs: ["Закупочная цена, KGS", "Purchase price, KGS", "Сатып алуу баасы, KGS"],
  avgCostKgs: ["Себестоимость, KGS", "Unit cost, KGS", "Өздүк нарк, KGS"],
  initialOnHand: ["Начальный остаток", "Opening stock", "Баштапкы калдык"],
  minStock: ["Минимальный остаток", "Minimum stock", "Минималдуу калдык"],
  sku: ["Артикул", "SKU", "Артикул"],
  description: ["Описание", "Description", "Сүрөттөмө"],
  category: ["Категория", "Category", "Категория"],
  categories: ["Категории", "Categories", "Категориялар"],
  barcodes: ["Штрихкоды", "Barcodes", "Штрихкоддор"],
  imageChoice: ["Фотография", "Photo", "Сүрөт"],
  attachmentId: ["Фотография", "Photo", "Сүрөт"],
  photo: ["Фотография", "Photo", "Сүрөт"],
  variants: ["Варианты товара", "Product variants", "Товардын варианттары"],
  addVariants: ["Добавить варианты", "Add variants", "Варианттарды кошуу"],
  attributes: ["Характеристики", "Attributes", "Мүнөздөмөлөр"],
  key: ["Характеристика", "Attribute", "Мүнөздөмө"],
  value: ["Значение", "Value", "Маани"],
  storePriceKgs: ["Цена в магазине, KGS", "Store price, KGS", "Дүкөндөгү баа, KGS"],
  supplierId: ["Поставщик", "Supplier", "Жеткирүүчү"],
  supplierName: ["Поставщик", "Supplier", "Жеткирүүчү"],
  customerId: ["Клиент", "Customer", "Кардар"],
  customerName: ["Имя клиента", "Customer name", "Кардардын аты"],
  customerEmail: ["Почта клиента", "Customer email", "Кардардын почтасы"],
  customerPhone: ["Телефон клиента", "Customer phone", "Кардардын телефону"],
  email: ["Электронная почта", "Email", "Электрондук почта"],
  phone: ["Телефон", "Phone", "Телефон"],
  address: ["Адрес", "Address", "Дарек"],
  lines: ["Товары", "Items", "Товарлар"],
  productId: ["Товар", "Product", "Товар"],
  productIds: ["Товары", "Products", "Товарлар"],
  variantId: ["Вариант товара", "Variant", "Товардын варианты"],
  qty: ["Количество", "Quantity", "Саны"],
  quantity: ["Количество", "Quantity", "Саны"],
  qtyOrdered: ["Заказать", "Order quantity", "Буйрутманын саны"],
  qtyReceived: ["Принять", "Receive quantity", "Кабыл алынган сан"],
  countedQty: ["Пересчитано", "Counted quantity", "Саналган саны"],
  countedQuantity: ["Пересчитано", "Counted quantity", "Саналган саны"],
  onHand: ["Фактический остаток", "Actual stock", "Иш жүзүндөгү калдык"],
  quantityDelta: ["Изменение количества (+/−)", "Quantity change (+/−)", "Сандын өзгөрүшү (+/−)"],
  delta: ["Изменение количества (+/−)", "Quantity change (+/−)", "Сандын өзгөрүшү (+/−)"],
  unitCost: ["Стоимость за единицу, KGS", "Unit cost, KGS", "Бирдиктин наркы, KGS"],
  unitPriceKgs: ["Цена за единицу, KGS", "Unit price, KGS", "Бирдиктин баасы, KGS"],
  note: ["Комментарий", "Comment", "Түшүндүрмө"],
  notes: ["Комментарий", "Comment", "Түшүндүрмө"],
  reason: ["Причина", "Reason", "Себеп"],
  referenceNumber: [
    "Номер документа поставщика",
    "Supplier reference",
    "Жеткирүүчүнүн документ номери",
  ],
  date: ["Дата документа", "Document date", "Документтин датасы"],
  submit: ["Отправить после сохранения", "Submit after saving", "Сактагандан кийин жөнөтүү"],
  registerId: ["Касса", "Register", "Касса"],
  saleId: ["Чек", "Receipt", "Чек"],
  originalSaleId: ["Исходный чек", "Original receipt", "Баштапкы чек"],
  customerOrderId: ["Заказ клиента", "Customer order", "Кардардын буйрутмасы"],
  purchaseOrderId: ["Заказ поставщику", "Purchase order", "Жеткирүүчүгө буйрутма"],
  saleReturnId: ["Возврат", "Return", "Кайтаруу"],
  stockCountId: ["Инвентаризация", "Stock count", "Инвентаризация"],
  lineId: ["Строка документа", "Document line", "Документтин сабы"],
  returnLineId: ["Строка возврата", "Return line", "Кайтаруунун сабы"],
  customerOrderLineId: ["Товар исходного чека", "Original receipt item", "Баштапкы чектин товары"],
  payments: ["Оплата", "Payment", "Төлөм"],
  method: ["Способ оплаты", "Payment method", "Төлөө ыкмасы"],
  amountKgs: ["Сумма, KGS", "Amount, KGS", "Сумма, KGS"],
  openingCashKgs: [
    "Наличные при открытии, KGS",
    "Opening cash, KGS",
    "Ачылыштагы накталай акча, KGS",
  ],
  isBundle: ["Комплект", "Bundle", "Топтом"],
  bundleComponents: ["Состав комплекта", "Bundle components", "Топтомдун курамы"],
  componentProductId: ["Товар в комплекте", "Component product", "Топтомдогу товар"],
  componentVariantId: ["Вариант компонента", "Component variant", "Курамдын варианты"],
  packs: ["Упаковки", "Packs", "Таңгактар"],
  packName: ["Название упаковки", "Pack name", "Таңгактын аталышы"],
  packBarcode: ["Штрихкод упаковки", "Pack barcode", "Таңгактын штрихкоду"],
  multiplierToBase: ["Единиц в упаковке", "Units per pack", "Таңгактагы бирдиктер"],
  allowInPurchasing: ["Для закупок", "Use for purchasing", "Сатып алууга"],
  allowInReceiving: ["Для оприходования", "Use for receiving", "Кириштөөгө"],
};
export const workflowEnums: Record<string, [string, string, string]> = {
  Брак: ["Брак", "Defect", "Кемчилик"],
  Порча: ["Порча", "Damage", "Бузулуу"],
  Просрочка: ["Просрочка", "Expired", "Мөөнөтү өткөн"],
  Потеря: ["Потеря", "Loss", "Жоготуу"],
  Кража: ["Кража", "Theft", "Уурдоо"],
  "Для внутреннего использования": [
    "Для внутреннего использования",
    "Internal use",
    "Ички колдонуу",
  ],
  Другое: ["Другое", "Other reason", "Башка себеп"],
  CASH: ["Наличные", "Cash", "Накталай"],
  CARD: ["Карта", "Card", "Карта"],
  TRANSFER: ["Перевод", "Transfer", "Которуу"],
  OTHER: ["Другой способ", "Other", "Башка"],
  without_photo: ["Без фотографии", "Without photo", "Сүрөтсүз"],
  attached_photo: ["Прикреплённая фотография", "Attached photo", "Тиркелген сүрөт"],
  keep: ["Оставить текущую", "Keep current photo", "Учурдагы сүрөттү калтыруу"],
  remove: ["Удалить фотографию", "Remove photo", "Сүрөттү өчүрүү"],
  attach: ["Заменить фотографию", "Replace photo", "Сүрөттү алмаштыруу"],
  DAMAGE: ["Повреждение", "Damage", "Бузулуу"],
  EXPIRED: ["Истёк срок годности", "Expired", "Мөөнөтү өткөн"],
  LOSS: ["Утрата", "Loss", "Жоготуу"],
  THEFT: ["Кража", "Theft", "Уурдоо"],
  INTERNAL_USE: ["Для своих нужд", "Internal use", "Ички колдонуу"],
  OTHER_REASON: ["Другая причина", "Other reason", "Башка себеп"],
};

export function localizeWorkflowFields(fields: WorkflowField[], locale: string): WorkflowField[] {
  return fields.map((f) => ({
    ...f,
    label: workflowLabels[f.key] ? baamText(locale, ...workflowLabels[f.key]) : f.label,
    options: f.options?.map((o) => ({
      ...o,
      label: workflowEnums[o.value] ? baamText(locale, ...workflowEnums[o.value]) : o.label,
    })),
    fields: f.fields ? localizeWorkflowFields(f.fields, locale) : undefined,
    item: f.item ? localizeWorkflowFields([f.item], locale)[0] : undefined,
  }));
}
