import { beforeEach, describe, expect, it } from "vitest";
import { prisma } from "@/server/db/prisma";
import { applyLoyaltyToOrder, confirmLoyaltyForOrder } from "@/server/services/loyalty/apply";
import { applyEntry, ensureAccount } from "@/server/services/loyalty/ledger";
import { upsertLoyaltyProgram } from "@/server/services/loyalty/program";
import { exportProductTableBatch } from "@/server/services/products/read";
import { createTestCaller } from "../helpers/context";
import { resetDatabase, seedBase, shouldRunDbTests } from "../helpers/db";

const describeDb = shouldRunDbTests ? describe : describe.skip;
describeDb("feature acceptance across money, prices, stock and exports", () => {
  beforeEach(resetDatabase);
  const fixture = async () => {
    const f = await seedBase({ plan: "ENTERPRISE" });
    await prisma.product.update({ where: { id: f.product.id }, data: { basePriceKgs: 1000 } });
    await prisma.store.update({ where: { id: f.store.id }, data: { retailWholesaleEnabled: true } });
    const caller = createTestCaller({ ...f.adminUser, organizationId: f.org.id });
    const cashier = createTestCaller({ ...f.cashierUser, organizationId: f.org.id });
    const register = await caller.pos.registers.create({ storeId: f.store.id, code: "FEATURE", name: "Acceptance" });
    const shift = await cashier.pos.shifts.open({ registerId: register.id, openingCashKgs: 0, idempotencyKey: "feature-open-shift" });
    await caller.inventory.postStockReceiving({ storeId: f.store.id, lines: [{ productId: f.product.id, quantity: 20, unitCost: 100 }], idempotencyKey: "feature-opening-stock" });
    return { ...f, caller, cashier, register, shift };
  };
  it("inherits standard prices, respects zero and preserves manual lines through mode changes and held receipts", async () => {
    const f = await fixture();
    await f.caller.storePrices.upsert({ storeId: f.store.id, productId: f.product.id, retailPriceKgs: null, wholesalePriceKgs: 800 });
    expect(await prisma.storePrice.count({ where: { productId: f.product.id } })).toBe(0);
    expect((await prisma.storePriceTypes.findFirstOrThrow({ where: { productId: f.product.id } })).retailPriceKgs).toBeNull();
    let sale = await f.cashier.pos.sales.createDraft({ registerId: f.register.id, priceMode: "RETAIL", lines: [{ productId: f.product.id, qty: 1 }] });
    let line = await prisma.customerOrderLine.findFirstOrThrow({ where: { customerOrderId: sale.id } });
    expect(Number(line.unitPriceKgs)).toBe(800);
    await f.caller.storePrices.upsert({ storeId: f.store.id, productId: f.product.id, retailPriceKgs: 0, wholesalePriceKgs: 900 });
    const preview = await f.cashier.posTools.changePriceMode({ saleId: sale.id, mode: "WHOLESALE" });
    expect(preview).toMatchObject({ needsConfirmation: true, totalKgs: 900 });
    expect(Number((await prisma.customerOrder.findUniqueOrThrow({ where: { id: sale.id } })).totalKgs)).toBe(800);
    await f.cashier.posTools.changePriceMode({ saleId: sale.id, mode: "WHOLESALE", confirmation: preview.fingerprint, expectedTotal: 900 });
    await f.cashier.pos.sales.updateLine({ lineId: line.id, unitPriceKgs: 777 });
    const manual = await f.cashier.posTools.changePriceMode({ saleId: sale.id, mode: "RETAIL" });
    expect(manual).toMatchObject({ needsConfirmation: false, totalKgs: 777 });
    line = await prisma.customerOrderLine.findUniqueOrThrow({ where: { id: line.id } });
    expect(line.manualPrice).toBe(true);
    expect(line.priceSource).toBe("MANUAL");
    await f.cashier.pos.sales.holdDraft({ saleId: sale.id });
    const held = await prisma.customerOrder.findUniqueOrThrow({ where: { id: sale.id } });
    expect(held.priceMode).toBe("RETAIL");
    await f.cashier.pos.sales.resumeHeldDraft({ saleId: sale.id, registerId: f.register.id });
    expect(Number((await prisma.customerOrderLine.findUniqueOrThrow({ where: { id: line.id } })).unitPriceKgs)).toBe(777);
    await f.cashier.pos.sales.cancelDraft({ saleId: sale.id });
    sale = await f.cashier.pos.sales.createDraft({ registerId: f.register.id, priceMode: "RETAIL", lines: [{ productId: f.product.id, qty: 1 }] });
    expect(Number((await prisma.customerOrder.findUniqueOrThrow({ where: { id: sale.id } })).totalKgs)).toBe(0);
  });
  it("preserves prices from legacy writers while automatic reprice and loyalty remain automatic", async () => {
    const f = await fixture();
    await f.caller.storePrices.upsert({ storeId: f.store.id, productId: f.product.id, retailPriceKgs: 1000, wholesalePriceKgs: 800 });
    const sale = await f.cashier.pos.sales.createDraft({ registerId: f.register.id, lines: [{ productId: f.product.id, qty: 1 }] });
    let line = await prisma.customerOrderLine.findFirstOrThrow({ where: { customerOrderId: sale.id } });
    expect(line.manualPrice).toBe(false);
    await prisma.customerOrderLine.update({ where: { id: line.id }, data: { qty: 2, lineTotalKgs: 2000 } });
    expect((await prisma.customerOrderLine.findUniqueOrThrow({ where: { id: line.id } })).manualPrice).toBe(false);
    const preview = await f.cashier.posTools.changePriceMode({ saleId: sale.id, mode: "WHOLESALE" });
    await f.cashier.posTools.changePriceMode({ saleId: sale.id, mode: "WHOLESALE", confirmation: preview.fingerprint, expectedTotal: 1600 });
    line = await prisma.customerOrderLine.findUniqueOrThrow({ where: { id: line.id } });
    expect(line.manualPrice).toBe(false);
    expect(line.unitPriceKgs.toNumber()).toBe(800);
    const program = await upsertLoyaltyProgram(prisma, f.org.id, { enabled: true, storeIds: [f.store.id] });
    const member = await prisma.loyaltyMember.create({ data: { organizationId: f.org.id, programId: program.id, contactKey: "email:legacy@example.invalid" } });
    await ensureAccount(prisma, { organizationId: f.org.id, programId: program.id, memberId: member.id });
    await prisma.$transaction(tx => applyLoyaltyToOrder(tx, { organizationId: f.org.id, storeId: f.store.id, customerOrderId: sale.id, memberId: member.id, requestedPoints: 0 }));
    expect((await prisma.customerOrderLine.findUniqueOrThrow({ where: { id: line.id } })).manualPrice).toBe(false);
    // The previous application sends base/discount columns on every manual edit,
    // including entering the same price. It knows neither provenance field.
    const retail = await f.cashier.posTools.changePriceMode({ saleId: sale.id, mode: "RETAIL" });
    await f.cashier.posTools.changePriceMode({ saleId: sale.id, mode: "RETAIL", confirmation: retail.fingerprint, expectedTotal: retail.totalKgs });
    line = await prisma.customerOrderLine.findUniqueOrThrow({ where: { id: line.id } });
    await prisma.customerOrderLine.update({ where: { id: line.id }, data: { baseUnitPriceKgs: line.baseUnitPriceKgs, appliedDiscountType: null, appliedDiscountPercentage: null, appliedDiscountAmountKgs: null } });
    expect((await prisma.customerOrderLine.findUniqueOrThrow({ where: { id: line.id } }))).toMatchObject({ manualPrice: true, priceSource: "MANUAL" });
    const legacyOrder = await prisma.customerOrder.create({ data: { organizationId: f.org.id, storeId: f.store.id, number: "LEGACY-WRITER" } });
    await prisma.$executeRaw`INSERT INTO "CustomerOrderLine" (id, "customerOrderId", "productId", qty, "unitPriceKgs", "lineTotalKgs") VALUES ('legacy-line', ${legacyOrder.id}, ${f.product.id}, 1, 777, 777)`;
    expect((await prisma.customerOrderLine.findUniqueOrThrow({ where: { id: "legacy-line" } }))).toMatchObject({ manualPrice: true, priceSource: "LEGACY" });
  });
  it("preserves an existing promo and exact line total when a legacy receipt changes price mode", async () => {
    const f = await fixture();
    await prisma.storePrice.create({ data: { organizationId: f.org.id, storeId: f.store.id, productId: f.product.id, priceKgs: 100, discountType: "PERCENTAGE", discountPercentage: 20 } });
    const sale = await f.cashier.pos.sales.createDraft({ registerId: f.register.id, lines: [{ productId: f.product.id, qty: 1 }] });
    const line = await prisma.customerOrderLine.findFirstOrThrow({ where: { customerOrderId: sale.id } });
    await prisma.customerOrderLine.update({ where: { id: line.id }, data: { priceSource: "LEGACY", manualPrice: true } });
    await f.cashier.posTools.changePriceMode({ saleId: sale.id, mode: "WHOLESALE" });
    const preserved = await prisma.customerOrderLine.findUniqueOrThrow({ where: { id: line.id } });
    expect(preserved.baseUnitPriceKgs?.toNumber()).toBe(100);
    expect(preserved.lineTotalKgs.toNumber()).toBe(80);
    expect(preserved.appliedDiscountPercentage?.toNumber()).toBe(20);
    const program = await upsertLoyaltyProgram(prisma, f.org.id, { enabled: true, storeIds: [f.store.id], excludePromoItems: true });
    const member = await prisma.loyaltyMember.create({ data: { organizationId: f.org.id, programId: program.id, contactKey: "email:legacy-promo@example.invalid" } });
    await ensureAccount(prisma, { organizationId: f.org.id, programId: program.id, memberId: member.id });
    const result = await prisma.$transaction(tx => applyLoyaltyToOrder(tx, { organizationId: f.org.id, storeId: f.store.id, customerOrderId: sale.id, memberId: member.id, requestedPoints: 0 }));
    expect(Number((await prisma.customerOrder.findUniqueOrThrow({ where: { id: sale.id } })).totalKgs)).toBe(80);
    expect(result.application.pointsEarned).toBe(0);
  });
  it("selects variant prices without changing base lines and keeps disabled stores on standard prices", async () => {
    const f = await fixture();
    const variant = await prisma.productVariant.create({ data: { productId: f.product.id, name: "Black", attributes: {} } });
    await f.caller.storePrices.upsert({ storeId: f.store.id, productId: f.product.id, variantId: variant.id, retailPriceKgs: 1200, wholesalePriceKgs: 0 });
    const sale = await f.cashier.pos.sales.createDraft({ registerId: f.register.id, priceMode: "WHOLESALE", lines: [{ productId: f.product.id, qty: 1 }, { productId: f.product.id, variantId: variant.id, qty: 1 }] });
    const lines = await prisma.customerOrderLine.findMany({ where: { customerOrderId: sale.id } });
    expect(lines.find(l => !l.variantId)?.unitPriceKgs.toNumber()).toBe(1000);
    expect(lines.find(l => l.variantId)?.unitPriceKgs.toNumber()).toBe(0);
    await f.cashier.pos.sales.cancelDraft({ saleId: sale.id });
    await prisma.store.update({ where: { id: f.store.id }, data: { retailWholesaleEnabled: false } });
    const disabled = await f.cashier.pos.sales.createDraft({ registerId: f.register.id, priceMode: "WHOLESALE", lines: [{ productId: f.product.id, variantId: variant.id, qty: 1 }] });
    expect(Number((await prisma.customerOrder.findUniqueOrThrow({ where: { id: disabled.id } })).totalKgs)).toBe(1000);
  });
  it("requires transfer permission, preserves the sale, and posts only one OUT/IN pair on replay", async () => {
    const f = await fixture();
    const destination = await prisma.store.create({ data: { organizationId: f.org.id, name: "Receiver", code: "OTHER" } });
    await prisma.userStoreAccess.create({ data: { organizationId: f.org.id, userId: f.cashierUser.id, storeId: destination.id } });
    const sale = await f.cashier.pos.sales.createDraft({ registerId: f.register.id, lines: [{ productId: f.product.id, qty: 1 }] });
    const input = { registerId: f.register.id, toStoreId: destination.id, lines: [{ productId: f.product.id, qty: 2 }], idempotencyKey: "feature-transfer-once" };
    await expect(f.cashier.posTools.transfer(input)).rejects.toMatchObject({ code: "FORBIDDEN" });
    await f.caller.users.setTransferPermission({ userId: f.cashierUser.id, enabled: true });
    await f.cashier.posTools.transfer(input);
    await f.cashier.posTools.transfer(input);
    expect((await prisma.inventorySnapshot.findFirstOrThrow({ where: { storeId: f.store.id, productId: f.product.id } })).onHand).toBe(18);
    expect((await prisma.inventorySnapshot.findFirstOrThrow({ where: { storeId: destination.id, productId: f.product.id } })).onHand).toBe(2);
    expect(await prisma.stockMovement.count({ where: { type: { in: ["TRANSFER_OUT", "TRANSFER_IN"] } } })).toBe(2);
    expect(await prisma.salePayment.count()).toBe(0);
    expect(await prisma.loyaltyLedgerEntry.count()).toBe(0);
    expect(Number((await prisma.customerOrder.findUniqueOrThrow({ where: { id: sale.id } })).totalKgs)).toBe(1000);
    await expect(f.cashier.posTools.transfer({ ...input, lines: [{ productId: f.product.id, qty: 19 }], idempotencyKey: "feature-transfer-short" })).rejects.toBeTruthy();
    await expect(f.cashier.posTools.transfer({ ...input, lines: [{ productId: f.product.id, qty: 3 }] })).rejects.toBeTruthy();
    expect((await prisma.inventorySnapshot.findFirstOrThrow({ where: { storeId: f.store.id, productId: f.product.id } })).onHand).toBe(18);
  });
  it("collects a completed online order in real shifts, earns only on full payment, and rejects concurrent overpayment", async () => {
    const f = await fixture();
    const program = await upsertLoyaltyProgram(prisma, f.org.id, { enabled: true, storeIds: [f.store.id] });
    const member = await prisma.loyaltyMember.create({ data: { organizationId: f.org.id, programId: program.id, contactKey: "email:late@example.invalid" } });
    const account = await ensureAccount(prisma, { organizationId: f.org.id, programId: program.id, memberId: member.id });
    await prisma.$transaction(tx => applyEntry(tx, { organizationId: f.org.id, programId: program.id, memberId: member.id, accountId: account.id, type: "ADJUSTMENT", points: 1000, eventKey: "opening" }));
    const order = await prisma.customerOrder.create({ data: { organizationId: f.org.id, storeId: f.store.id, number: "ONLINE-LATE", saleChannel: "ONLINE", subtotalKgs: 1000, totalKgs: 1000, lines: { create: { productId: f.product.id, qty: 4, unitPriceKgs: 250, baseUnitPriceKgs: 250, lineTotalKgs: 1000 } } } });
    await prisma.$transaction(tx => applyLoyaltyToOrder(tx, { organizationId: f.org.id, storeId: f.store.id, customerOrderId: order.id, memberId: member.id, requestedPoints: 475 }));
    await prisma.customerOrder.update({ where: { id: order.id }, data: { status: "COMPLETED", completedAt: new Date() } });
    await prisma.$transaction(tx => confirmLoyaltyForOrder(tx, { organizationId: f.org.id, customerOrderId: order.id, paidInFull: false }));
    await expect(f.cashier.pos.returns.createDraft({ originalSaleId: order.id, shiftId: f.shift.id })).rejects.toMatchObject({ message: "onlineReturnRequiresPayment" });
    const payment = { customerOrderId: order.id, shiftId: f.shift.id, amountKgs: 200, method: "CASH" as const, idempotencyKey: "online-partial-payment" };
    await f.cashier.salesOrders.recordPayment(payment);
    await f.cashier.salesOrders.recordPayment(payment);
    expect((await prisma.loyaltyAccount.findUniqueOrThrow({ where: { id: account.id } })).balancePoints).toBe(525);
    await expect(f.cashier.pos.returns.createDraft({ originalSaleId: order.id, shiftId: f.shift.id })).rejects.toMatchObject({ message: "onlineReturnRequiresPayment" });
    expect((await f.cashier.pos.shifts.xReport({ shiftId: f.shift.id })).summary.expectedCashKgs).toBe(200);
    await f.cashier.pos.shifts.close({ shiftId: f.shift.id, closingCashCountedKgs: 200, idempotencyKey: "close-first-shift" });
    const second = await f.cashier.pos.shifts.open({ registerId: f.register.id, openingCashKgs: 0, idempotencyKey: "open-second-shift" });
    const payments = await Promise.allSettled(["a", "b"].map(key => f.cashier.salesOrders.recordPayment({ ...payment, shiftId: second.id, amountKgs: 275, idempotencyKey: `online-last-payment-${key}` })));
    expect(payments.filter(p => p.status === "fulfilled")).toHaveLength(1);
    expect((await f.cashier.pos.shifts.xReport({ shiftId: second.id })).summary.expectedCashKgs).toBe(275);
    expect((await prisma.loyaltyAccount.findUniqueOrThrow({ where: { id: account.id } })).balancePoints).toBe(548);
    expect(await prisma.salePayment.count({ where: { customerOrderId: order.id } })).toBe(2);
    expect((await prisma.customerOrder.findUniqueOrThrow({ where: { id: order.id } }))).toMatchObject({ isPosSale: false, saleChannel: "ONLINE", shiftId: null });
    const line = await prisma.customerOrderLine.findFirstOrThrow({ where: { customerOrderId: order.id } });
    for (const [qty, amount, balance] of [[1, 118.75, 661], [3, 356.25, 1000]]) {
      const refund = await f.cashier.pos.returns.createDraft({ originalSaleId: order.id, shiftId: second.id });
      await f.cashier.pos.returns.addLine({ saleReturnId: refund.id, customerOrderLineId: line.id, qty });
      const payload = { saleReturnId: refund.id, idempotencyKey: `online-refund-${qty}`, payments: [{ method: "CASH" as const, amountKgs: amount }] };
      await f.cashier.pos.returns.complete(payload); await f.cashier.pos.returns.complete(payload);
      expect((await prisma.loyaltyAccount.findUniqueOrThrow({ where: { id: account.id } })).balancePoints).toBe(balance);
    }
    expect((await prisma.salePayment.aggregate({ where: { customerOrderId: order.id, isRefund: true }, _sum: { amountKgs: true } }))._sum.amountKgs?.toNumber()).toBe(475);
  });
  it("limits a manually discounted receipt refund to the 80 actually paid", async () => {
    const f = await fixture();
    const sale = await f.cashier.pos.sales.createDraft({ registerId: f.register.id, lines: [{ productId: f.product.id, qty: 1 }] });
    const line = await prisma.customerOrderLine.findFirstOrThrow({ where: { customerOrderId: sale.id } });
    await f.cashier.pos.sales.updateLine({ lineId: line.id, unitPriceKgs: 100 });
    await f.cashier.pos.sales.updateDiscount({ saleId: sale.id, discountKgs: 20 });
    await f.cashier.pos.sales.complete({ saleId: sale.id, payments: [{ method: "CASH", amountKgs: 80 }], idempotencyKey: "manual-discount-paid" });
    const refund = await f.cashier.pos.returns.createDraft({ originalSaleId: sale.id, shiftId: f.shift.id });
    await f.cashier.pos.returns.addLine({ saleReturnId: refund.id, customerOrderLineId: line.id, qty: 1 });
    expect((await f.cashier.pos.returns.get({ saleReturnId: refund.id }))?.totalKgs).toBe(80);
    await expect(f.cashier.pos.returns.complete({ saleReturnId: refund.id, payments: [{ method: "CASH", amountKgs: 100 }], idempotencyKey: "refund-too-much" })).rejects.toBeTruthy();
    await f.cashier.pos.returns.complete({ saleReturnId: refund.id, payments: [{ method: "CASH", amountKgs: 80 }], idempotencyKey: "refund-correct" });
    expect((await f.cashier.pos.shifts.xReport({ shiftId: f.shift.id })).summary.expectedCashKgs).toBe(0);
  });
  it("refunds the remaining 80 after a paid 100 receipt was corrected down, and rejects increasing its refund above the tender", async () => {
    const f = await fixture();
    const sale = await f.cashier.pos.sales.createDraft({ registerId: f.register.id, lines: [{ productId: f.product.id, qty: 1 }] });
    const source = await prisma.customerOrderLine.findFirstOrThrow({ where: { customerOrderId: sale.id } });
    await f.cashier.pos.sales.updateLine({ lineId: source.id, unitPriceKgs: 100 });
    await f.cashier.pos.sales.complete({ saleId: sale.id, payments: [{ method: "CASH", amountKgs: 100 }], idempotencyKey: "correction-original-paid" });
    await f.caller.pos.sales.editCompleted({ saleId: sale.id, lines: [{ lineId: source.id, productId: f.product.id, qty: 1, unitPriceKgs: 80 }], discountKgs: 0, idempotencyKey: "receipt-corrected-to-eighty" });
    const refund = await f.cashier.pos.returns.createDraft({ originalSaleId: sale.id, shiftId: f.shift.id });
    await f.cashier.pos.returns.addLine({ saleReturnId: refund.id, customerOrderLineId: source.id, qty: 1 });
    await f.cashier.pos.returns.complete({ saleReturnId: refund.id, payments: [{ method: "CASH", amountKgs: 80 }], idempotencyKey: "corrected-sale-returned" });
    const returnedLine = await prisma.saleReturnLine.findFirstOrThrow({ where: { saleReturnId: refund.id } });
    await expect(f.caller.pos.returns.editCompleted({ saleReturnId: refund.id, lines: [{ lineId: returnedLine.id, customerOrderLineId: source.id, productId: f.product.id, qty: 1, unitPriceKgs: 1000 }], idempotencyKey: "excess-refund-correction" })).rejects.toMatchObject({ message: "posPaymentTotalMismatch" });
    expect(Number((await prisma.saleReturn.findUniqueOrThrow({ where: { id: refund.id } })).totalKgs)).toBe(80);
    expect((await f.cashier.pos.shifts.xReport({ shiftId: f.shift.id })).summary.expectedCashKgs).toBe(0);
  });
  it("keeps completed online return money immutable even without loyalty", async () => {
    const f = await fixture();
    const order = await prisma.customerOrder.create({ data: { organizationId: f.org.id, storeId: f.store.id, number: "ONLINE-NO-BONUS", saleChannel: "ONLINE", subtotalKgs: 100, totalKgs: 100, lines: { create: { productId: f.product.id, qty: 1, unitPriceKgs: 100, lineTotalKgs: 100 } } } });
    await f.caller.salesOrders.confirm({ customerOrderId: order.id });
    await f.caller.salesOrders.markReady({ customerOrderId: order.id });
    await f.caller.salesOrders.complete({ customerOrderId: order.id, idempotencyKey: "online-no-bonus-complete" });
    await f.cashier.salesOrders.recordPayment({ customerOrderId: order.id, shiftId: f.shift.id, amountKgs: 100, method: "CASH", idempotencyKey: "online-no-bonus-paid" });
    const source = await prisma.customerOrderLine.findFirstOrThrow({ where: { customerOrderId: order.id } });
    const refund = await f.cashier.pos.returns.createDraft({ originalSaleId: order.id, shiftId: f.shift.id });
    await f.cashier.pos.returns.addLine({ saleReturnId: refund.id, customerOrderLineId: source.id, qty: 1 });
    await f.cashier.pos.returns.complete({ saleReturnId: refund.id, payments: [{ method: "CASH", amountKgs: 100 }], idempotencyKey: "online-no-bonus-return" });
    const returnedLine = await prisma.saleReturnLine.findFirstOrThrow({ where: { saleReturnId: refund.id } });
    await expect(f.caller.pos.returns.editCompleted({ saleReturnId: refund.id, lines: [{ lineId: returnedLine.id, customerOrderLineId: source.id, productId: f.product.id, qty: 1, unitPriceKgs: 1000 }], idempotencyKey: "online-return-edit-rejected" })).rejects.toMatchObject({ message: "onlineReturnFinancialEdit" });
    expect((await prisma.salePayment.aggregate({ where: { customerOrderId: order.id, isRefund: true }, _sum: { amountKgs: true } }))._sum.amountKgs?.toNumber()).toBe(100);
  });
  it("deletes unused products and variants with extra prices through the existing delete flow", async () => {
    const f = await fixture();
    const product = await prisma.product.create({ data: { organizationId: f.org.id, name: "Unused", sku: "UNUSED", unit: f.product.unit, baseUnitId: f.baseUnit.id } });
    const variant = await prisma.productVariant.create({ data: { productId: product.id, name: "Unused variant", attributes: {} } });
    await f.caller.storePrices.upsert({ storeId: f.store.id, productId: product.id, retailPriceKgs: 100 });
    await f.caller.storePrices.upsert({ storeId: f.store.id, productId: product.id, variantId: variant.id, wholesalePriceKgs: 80 });
    await f.caller.products.deletePermanent({ productId: product.id });
    expect(await prisma.storePriceTypes.count({ where: { productId: product.id } })).toBe(0);
    expect(await prisma.product.findUnique({ where: { id: product.id } })).toBeNull();
  });
  it("refunds online CARD payments and keeps a negative bonus balance after earned points were spent", async () => {
    const f = await fixture();
    const program = await upsertLoyaltyProgram(prisma, f.org.id, { enabled: true, storeIds: [f.store.id] });
    const member = await prisma.loyaltyMember.create({ data: { organizationId: f.org.id, programId: program.id, contactKey: "email:returns@example.invalid" } });
    const account = await ensureAccount(prisma, { organizationId: f.org.id, programId: program.id, memberId: member.id });
    const order = await prisma.customerOrder.create({ data: { organizationId: f.org.id, storeId: f.store.id, number: "ONLINE-CARD", saleChannel: "ONLINE", subtotalKgs: 64.32, totalKgs: 64.32, lines: { create: { productId: f.product.id, qty: 3, unitPriceKgs: 21.44, baseUnitPriceKgs: 21.44, lineTotalKgs: 64.32 } } } });
    await prisma.$transaction(tx => applyLoyaltyToOrder(tx, { organizationId: f.org.id, storeId: f.store.id, customerOrderId: order.id, memberId: member.id, requestedPoints: 0 }));
    await f.caller.salesOrders.confirm({ customerOrderId: order.id });
    await f.caller.salesOrders.markReady({ customerOrderId: order.id });
    await f.caller.salesOrders.complete({ customerOrderId: order.id, idempotencyKey: "online-card-complete" });
    await f.cashier.salesOrders.recordPayment({ customerOrderId: order.id, shiftId: f.shift.id, amountKgs: 61.10, method: "CARD", idempotencyKey: "online-card-paid" });
    expect((await prisma.loyaltyAccount.findUniqueOrThrow({ where: { id: account.id } })).balancePoints).toBe(3);
    await upsertLoyaltyProgram(prisma, f.org.id, { maxSpendPercent: 100 });
    const next = await f.cashier.pos.sales.createDraft({ registerId: f.register.id, lines: [{ productId: f.product.id, qty: 1 }] });
    const nextLine = await prisma.customerOrderLine.findFirstOrThrow({ where: { customerOrderId: next.id } });
    await f.cashier.pos.sales.updateLine({ lineId: nextLine.id, unitPriceKgs: 3.16 });
    await prisma.$transaction(tx => applyLoyaltyToOrder(tx, { organizationId: f.org.id, storeId: f.store.id, customerOrderId: next.id, memberId: member.id, requestedPoints: 3 }));
    await f.cashier.pos.sales.complete({ saleId: next.id, payments: [], idempotencyKey: "spend-earned-three" });
    expect((await prisma.loyaltyAccount.findUniqueOrThrow({ where: { id: account.id } })).balancePoints).toBe(0);
    const source = await prisma.customerOrderLine.findFirstOrThrow({ where: { customerOrderId: order.id } });
    const first = await f.cashier.pos.returns.createDraft({ originalSaleId: order.id, shiftId: f.shift.id, idempotencyKey: "online-refund-create-once" });
    expect((await f.cashier.pos.returns.createDraft({ originalSaleId: order.id, shiftId: f.shift.id, idempotencyKey: "online-refund-create-once" })).id).toBe(first.id);
    await f.cashier.pos.returns.addLine({ saleReturnId: first.id, customerOrderLineId: source.id, qty: 1 });
    await f.cashier.pos.returns.complete({ saleReturnId: first.id, payments: [{ method: "CARD", amountKgs: 20.37 }], idempotencyKey: "first-third-return" });
    expect((await prisma.loyaltyAccount.findUniqueOrThrow({ where: { id: account.id } })).balancePoints).toBe(-1);
    const drafts = [];
    for (const key of ["one", "two"]) {
      const refund = await f.cashier.pos.returns.createDraft({ originalSaleId: order.id, shiftId: f.shift.id, idempotencyKey: `concurrent-return-${key}` });
      await f.cashier.pos.returns.addLine({ saleReturnId: refund.id, customerOrderLineId: source.id, qty: 2 }); drafts.push(refund);
    }
    const results = await Promise.allSettled(drafts.map(refund => f.cashier.pos.returns.complete({ saleReturnId: refund.id, payments: [{ method: "CARD", amountKgs: 40.73 }], idempotencyKey: `complete-${refund.id}` })));
    expect(results.filter(result => result.status === "fulfilled")).toHaveLength(1);
    expect((await prisma.loyaltyAccount.findUniqueOrThrow({ where: { id: account.id } })).balancePoints).toBe(-3);
    expect((await prisma.salePayment.aggregate({ where: { customerOrderId: order.id, isRefund: true }, _sum: { amountKgs: true } }))._sum.amountKgs?.toNumber()).toBe(61.10);
  });
  it("exports every filtered page, honors selected IDs and hides cost data from cashiers", async () => {
    const f = await fixture();
    await prisma.product.createMany({ data: Array.from({ length: 501 }, (_, i) => ({ id: `export-${String(i).padStart(4, "0")}`, organizationId: f.org.id, sku: `EXPORT-${i}`, name: `Экспорт ${i}`, baseUnitId: f.baseUnit.id, unit: "each" })) });
    await prisma.storeProduct.createMany({ data: Array.from({ length: 501 }, (_, i) => ({ organizationId: f.org.id, storeId: f.store.id, productId: `export-${String(i).padStart(4, "0")}`, isActive: true })) });
    const args = { prisma, organizationId: f.org.id, user: { ...f.adminUser, organizationId: f.org.id }, storeId: f.store.id, input: { search: "EXPORT-", readiness: "missingCost" as const } };
    const first = await exportProductTableBatch(args);
    const second = await exportProductTableBatch({ ...args, afterId: first.nextId });
    expect(first.rows).toHaveLength(500); expect(first.hasMore).toBe(true); expect(second.rows).toHaveLength(1);
    const selected = await exportProductTableBatch({ ...args, ids: ["export-0001", "export-0500", f.product.id] });
    expect(selected.rows.map(r => r.sku).sort()).toEqual(["EXPORT-1", "EXPORT-500"]);
    const cashier = await exportProductTableBatch({ ...args, user: { ...f.cashierUser, organizationId: f.org.id }, input: { search: "EXPORT-" }, columns: ["sku", "onHandQty", "avgCostKgs", "purchasePriceKgs"] });
    expect(cashier.keys).toEqual(["sku", "onHandQty"]);
    await expect(exportProductTableBatch({ ...args, user: { ...f.cashierUser, organizationId: f.org.id } })).rejects.toMatchObject({ code: "FORBIDDEN" });
  });
});
