"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { useTranslations } from "next-intl";
import { useSession } from "next-auth/react";

import { PageHeader } from "@/components/page-header";
import { ProductForm } from "@/components/product-form";
import { trpc } from "@/lib/trpc";
import { translateError } from "@/lib/translateError";
import { useToast } from "@/components/ui/toast";

const NewProductPage = () => {
  const t = useTranslations("products");
  const tCommon = useTranslations("common");
  const tErrors = useTranslations("errors");
  const router = useRouter();
  const searchParams = useSearchParams();
  const barcode = searchParams?.get("barcode")?.trim() ?? "";
  const requestedType = searchParams?.get("type")?.trim() ?? "";
  const isBundleDefault = requestedType === "bundle";
  const pageTitle = isBundleDefault ? t("newBundle") : t("newTitle");
  const pageSubtitle = isBundleDefault ? t("newBundleSubtitle") : t("newSubtitle");
  const { data: session, status } = useSession();
  const isAdmin = session?.user?.role === "ADMIN";
  const { toast } = useToast();
  const attributesQuery = trpc.attributes.list.useQuery();
  const unitsQuery = trpc.units.list.useQuery();
  const storesQuery = trpc.stores.list.useQuery(undefined, {
    enabled: status === "authenticated" && isAdmin,
  });
  const suggestedSkuQuery = trpc.products.suggestSku.useQuery(undefined, {
    enabled: status === "authenticated" && isAdmin,
  });

  const createMutation = trpc.products.create.useMutation({
    onSuccess: (product) => {
      toast({ variant: "success", description: t("createSuccess") });
      router.push(`/products/${product.id}`);
    },
    onError: (error) => {
      toast({ variant: "error", description: translateError(tErrors, error) });
    },
  });

  if (session && !isAdmin) {
    return (
      <div>
        <PageHeader title={pageTitle} subtitle={pageSubtitle} />
        <p className="mt-4 text-sm text-danger">{tErrors("forbidden")}</p>
      </div>
    );
  }

  if (status === "loading") {
    return (
      <div>
        <PageHeader title={pageTitle} subtitle={pageSubtitle} />
        <p className="mt-4 text-sm text-muted-foreground">{tCommon("loading")}</p>
      </div>
    );
  }

  if (isAdmin && suggestedSkuQuery.isLoading) {
    return (
      <div>
        <PageHeader title={pageTitle} subtitle={pageSubtitle} />
        <p className="mt-4 text-sm text-muted-foreground">{t("skuAutoGeneratedHint")}</p>
      </div>
    );
  }

  const suggestedSku = suggestedSkuQuery.data ?? "";
  const defaultCurrencyStore = storesQuery.data?.[0] ?? null;
  const defaultCurrencyRate = Number(defaultCurrencyStore?.currencyRateKgsPerUnit ?? 1);

  return (
    <div>
      <PageHeader title={pageTitle} subtitle={pageSubtitle} />
      <ProductForm
        key={`new:${defaultCurrencyStore?.currencyCode ?? "KGS"}:${defaultCurrencyRate}`}
        initialValues={{
          sku: suggestedSku,
          name: "",
          isBundle: isBundleDefault,
          category: "",
          categories: [],
          baseUnitId: "",
          basePriceKgs: undefined,
          purchasePriceKgs: undefined,
          avgCostKgs: undefined,
          description: "",
          photoUrl: "",
          images: [],
          barcodes: barcode ? [barcode] : [],
          packs: [],
          variants: [],
          bundleComponents: [],
        }}
        attributeDefinitions={attributesQuery.data ?? []}
        units={unitsQuery.data ?? []}
        onSubmit={(values) =>
          createMutation.mutate({
            ...values,
            sku: suggestedSku && values.sku.trim() === suggestedSku ? "" : values.sku,
          })
        }
        isSubmitting={createMutation.isLoading}
        currencyCode={defaultCurrencyStore?.currencyCode ?? null}
        currencyRateKgsPerUnit={defaultCurrencyRate}
        quickCreateMode
      />
      {createMutation.error ? (
        <p className="mt-3 text-sm text-danger">{translateError(tErrors, createMutation.error)}</p>
      ) : null}
    </div>
  );
};

export default NewProductPage;
