ALTER TABLE "StorePrinterSettings"
  ADD COLUMN "labelRollGapMm" DOUBLE PRECISION NOT NULL DEFAULT 3.5,
  ADD COLUMN "labelRollXOffsetMm" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "labelRollYOffsetMm" DOUBLE PRECISION NOT NULL DEFAULT 0;
