-- Add new export types
ALTER TYPE "ExportType" ADD VALUE IF NOT EXISTS 'INVENTORY_MOVEMENTS_LEDGER';
ALTER TYPE "ExportType" ADD VALUE IF NOT EXISTS 'INVENTORY_BALANCES_AT_DATE';
ALTER TYPE "ExportType" ADD VALUE IF NOT EXISTS 'PURCHASES_RECEIPTS';
ALTER TYPE "ExportType" ADD VALUE IF NOT EXISTS 'PRICE_LIST';

-- Extend ExportJob metadata fields
ALTER TABLE "ExportJob" ADD COLUMN IF NOT EXISTS "startedAt" TIMESTAMP(3);
ALTER TABLE "ExportJob" ADD COLUMN IF NOT EXISTS "paramsJson" JSONB;
ALTER TABLE "ExportJob" ADD COLUMN IF NOT EXISTS "errorJson" JSONB;
