import type {
  ProductMovementDocumentDetail,
  ProductMovementDocumentType,
} from "@/server/services/productMovements";
import type { MovementPrintDocumentLabels } from "@/components/inventory/movement-print-document";

export const movementPrintLabels: MovementPrintDocumentLabels = {
  companyFallback: "Bazaar",
  documentNumber: "Документ № PRINT-TEST",
  date: "Дата",
  status: "Статус",
  store: "Магазин",
  sourceStore: "Со склада",
  destinationStore: "На склад",
  receivingStore: "Склад-получатель",
  writeOffStore: "Склад",
  sender: "Отправитель",
  author: "Автор",
  reason: "Основание",
  comment: "Комментарий",
  product: "Товар",
  quantity: "Количество",
  unit: "Ед.",
  unitCost: "Цена",
  lineTotal: "Сумма",
  positions: "Позиций",
  amount: "Итого",
  costNotSpecified: "Не указано",
  shippedBy: "Отпустил",
  releasedBy: "Передал",
  writtenOffBy: "Списал",
  receivedBy: "Получил",
  checkedBy: "Проверил",
  responsible: "Ответственный",
  signatureDate: "Дата подписи",
  notAvailable: "—",
  statusLabel: "Проведён",
  title: "Накладная на оприходование",
};

// Synthetic presentation input only: no database, stock mutations or cost calculations.
export const movementPrintFixture = (
  documentType: ProductMovementDocumentType = "STOCK_RECEIVING",
  count = 90,
): ProductMovementDocumentDetail => ({
  id: "print-fixture",
  documentId: "print-fixture",
  documentType,
  documentNumber: "PRINT-TEST",
  documentLabel: "Synthetic print fixture",
  organizationName: "Тестовая организация — образец печати",
  isPosSale: false,
  createdAt: new Date("2026-09-07T06:00:00Z"),
  postedAt: new Date("2026-09-07T06:00:00Z"),
  status: "POSTED",
  paymentStatus: "NOT_APPLICABLE",
  orderStatus: null,
  senderName: "Тестовый отправитель",
  recipientName: "Тестовый получатель",
  storeName: "Тестовый склад",
  authorName: "Тестовый сотрудник",
  authorEmail: null,
  positionsCount: count,
  totalQuantity: count * 2,
  totalAmount: count * 35,
  paidAmount: null,
  reason: "Проверка печатной формы",
  comment: "Синтетические данные",
  description: null,
  detailUrl: null,
  sourceStoreId: "print-source",
  destinationStoreId: "print-target",
  lines: Array.from({ length: count }, (_, index) => ({
    id: `print-line-${index + 1}`,
    productId: `print-product-${index + 1}`,
    variantId: null,
    storeId: "print-source",
    productDetailUrl: `/products/print-product-${index + 1}`,
    storeName: "Тестовый склад",
    productName: `ROW${String(index + 1).padStart(3, "0")} Тестовый товар${index % 11 === 0 ? " с длинным названием для проверки переноса текста" : ""}`,
    sku: `SKU-ONLY-IN-DATA-${index + 1}`,
    barcode: `999000${String(index + 1).padStart(7, "0")}`,
    unit: "шт",
    variantName: index % 7 === 0 ? "Синий / XL" : null,
    movementType: documentType === "TRANSFER" ? "TRANSFER_OUT" : "RECEIVE",
    qtyDelta: 2,
    linePosition: index + 1,
    unitCostKgs: 17.5,
    lineTotalKgs: 35,
    note: null,
    createdAt: new Date("2026-09-07T06:00:00Z"),
    authorName: "Тестовый сотрудник",
    authorEmail: null,
  })),
});
