export const helpCaptureTargets = [
  { name: "dashboard-wide", path: "/dashboard", width: 1920, height: 1080 },
  { name: "products-wide", path: "/products", width: 1920, height: 1080 },
  { name: "product-create", path: "/products/new", width: 1920, height: 1080 },
  { name: "receiving", path: "/inventory/receiving", width: 1920, height: 1080 },
  { name: "transfer", path: "/inventory/transfers", width: 1920, height: 1080 },
  { name: "write-off", path: "/inventory/write-offs", width: 1920, height: 1080 },
  { name: "inventory-count", path: "/inventory/counts", width: 1920, height: 1080 },
  { name: "movements-wide", path: "/inventory/movements", width: 1920, height: 1080 },
  { name: "pos-desktop-wide", path: "/pos/sell", width: 1920, height: 1080 },
  { name: "pos-mobile", path: "/pos/sell", width: 390, height: 844 },
  { name: "pos-entry", path: "/pos", width: 390, height: 844 },
  { name: "shift-close", path: "/pos/shifts", width: 1920, height: 1080 },
  { name: "analytics", path: "/reports/analytics", width: 1920, height: 1080 },
  {
    name: "integrations-wide",
    path: "/operations/integrations",
    width: 1920,
    height: 1080,
  },
] as const;
